server:
  port: 9000
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: awdsd123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 2

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace